# Generated by Django 5.2.7 on 2026-02-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxclass',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taxclass',
            name='page',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='tax_class',
        ),
        migrations.RemoveField(
            model_name='taxexemptcustomer',
            name='tax_classes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_class',
        ),
        migrations.RemoveField(
            model_name='taxexemptcustomer',
            name='page',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='page',
        ),
        migrations.DeleteModel(
            name='CartTaxItem',
        ),
        migrations.DeleteModel(
            name='TaxClass',
        ),
        migrations.DeleteModel(
            name='TaxExemptCustomer',
        ),
        migrations.DeleteModel(
            name='TaxRate',
        ),
    ]
