# Generated by Django 5.2.7 on 2026-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_taxclass_unique_together_remove_taxclass_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
