# Generated by Django 5.2.7 on 2026-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_taxclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
