# Generated by Django 5.2.7 on 2026-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_taxexemptcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTaxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
