# Generated by Django 5.2.7 on 2026-02-11 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_carttaxitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxclass',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='taxclass',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description'),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Apply this tax class by default'),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='is_shipping_taxable',
            field=models.BooleanField(default=False, help_text='Apply tax to shipping rates'),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., Standard, Reduced, Food, Books', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_classes', to='builder.publishedpage'),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='taxclass',
            unique_together={('page', 'slug')},
        ),
    ]
