# Generated by Django 5.2.7 on 2026-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_alter_taxclass_options_taxclass_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
