# Generated by Django 5.2.7 on 2026-02-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_taxclass_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AddField(
            model_name='taxrate',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 2-letter country code', max_length=2),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_compound',
            field=models.BooleanField(default=False, help_text='Apply on top of other taxes'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_price_inclusive',
            field=models.BooleanField(default=False, help_text='Prices include this tax'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_shipping_taxable',
            field=models.BooleanField(default=False, help_text='Apply to shipping costs'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='jurisdiction_type',
            field=models.CharField(choices=[('country', 'Country'), ('state', 'State/Province'), ('city', 'City'), ('district', 'District'), ('postal_code', 'Postal Code')], default='country', max_length=20),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., US Sales Tax, EU VAT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='builder.publishedpage'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='postal_code_match_pattern',
            field=models.CharField(blank=True, help_text='Regex pattern for postal codes', max_length=50),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower numbers applied first'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tax rate (e.g., 10.0000 for 10%)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='state_code',
            field=models.CharField(blank=True, help_text='State/province code', max_length=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='builder.taxclass'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['page', 'is_active'], name='builder_tax_page_id_40c5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['country_code', 'state_code'], name='builder_tax_country_c8ed42_idx'),
        ),
    ]
