# Generated by Django 5.2.7 on 2026-02-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_alter_taxrate_options_taxrate_calculation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='applies_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='exempt_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='exemption_certificate',
            field=models.FileField(blank=True, null=True, upload_to='tax_exemptions/'),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_exempt_customers', to='builder.publishedpage'),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='tax_classes',
            field=models.ManyToManyField(blank=True, related_name='exempt_customers', to='builder.taxclass'),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='tax_id',
            field=models.CharField(blank=True, help_text='VAT ID, Tax ID, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='valid_from',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taxexemptcustomer',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
