# Generated by Django 5.2.7 on 2026-02-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_taxexemptcustomer_applies_to_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttaxitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carttaxitem',
            name='is_shipping_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carttaxitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.publishedpage'),
        ),
        migrations.AddField(
            model_name='carttaxitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carttaxitem',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carttaxitem',
            name='tax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.taxclass'),
        ),
        migrations.AddField(
            model_name='carttaxitem',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.taxrate'),
        ),
        migrations.AddField(
            model_name='carttaxitem',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='carttaxitem',
            index=models.Index(fields=['session_key', 'page'], name='builder_car_session_424c70_idx'),
        ),
    ]
