# Generated by Django 5.2.7 on 2026-02-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_carttaxitem_created_at_carttaxitem_is_shipping_tax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeFirts',
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='builder.taxclass'),
        ),
        migrations.AlterField(
            model_name='taxclass',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxexemptcustomer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
