# Generated by Django 5.2.7 on 2026-02-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_alter_taxclass_options_taxclass_created_at_and_more'),
        ('builder', '0013_delete_homefirts_product_tax_class_and_more'),
    ]

    operations = [
    ]
