# Generated by Django 5.2.7 on 2026-02-12 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_merge_20260212_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('neutral', 'Neutral & Minimal'), ('corporate', 'Corporate & Professional'), ('creative', 'Creative & Vibrant'), ('ecommerce', 'E-Commerce'), ('luxury', 'Luxury & Premium'), ('nature', 'Nature & Organic'), ('tech', 'Technology & Modern'), ('health', 'Health & Wellness'), ('education', 'Education'), ('food', 'Food & Beverage')], default='corporate', max_length=50)),
                ('mood', models.CharField(choices=[('professional', 'Professional'), ('playful', 'Playful'), ('elegant', 'Elegant'), ('energetic', 'Energetic'), ('calm', 'Calm'), ('trustworthy', 'Trustworthy'), ('luxurious', 'Luxurious'), ('modern', 'Modern'), ('warm', 'Warm'), ('cool', 'Cool')], default='professional', max_length=50)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this palette has been used')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
                'ordering': ['-display_order', '-usage_count', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='taxclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxclass',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., Standard, Reduced, Food, Books', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxclass',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_classes', to='builder.publishedpage'),
        ),
        migrations.AlterField(
            model_name='taxclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
