# Generated by Django 5.2.7 on 2026-02-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_colorpalette_alter_taxclass_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
