# Generated by Django 5.2.7 on 2026-02-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_alter_taxclass_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPaletteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Primary', 'Secondary', 'Accent'", max_length=100)),
                ('variable_name', models.CharField(db_index=True, help_text='CSS variable name (without --)', max_length=100)),
                ('hex_value', models.CharField(help_text='Hex color code (e.g., #4361ee)', max_length=7)),
                ('rgb_value', models.CharField(blank=True, help_text='RGB values (e.g., 67, 97, 238)', max_length=30)),
                ('color_type', models.CharField(choices=[('primary', 'Primary Brand Color'), ('secondary', 'Secondary Brand Color'), ('accent', 'Accent Color'), ('background', 'Background'), ('text', 'Text Color'), ('heading', 'Heading Color'), ('link', 'Link Color'), ('success', 'Success State'), ('warning', 'Warning State'), ('error', 'Error State'), ('info', 'Info State'), ('border', 'Border Color'), ('shadow', 'Shadow Color'), ('overlay', 'Overlay Color')], default='primary', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='builder.colorpalette')),
            ],
            options={
                'ordering': ['display_order', 'color_type'],
                'unique_together': {('palette', 'variable_name')},
            },
        ),
    ]
