# Generated by Django 5.2.7 on 2026-02-12 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_colorpalettecolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_colors', models.JSONField(default=dict, help_text='Snapshot of applied colors')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_palettes', to='builder.publishedpage')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.colorpalette')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('page', 'is_active')},
            },
        ),
    ]
