# Generated by Django 5.2.7 on 2026-02-12 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_pagecolorpalette'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('hex_value', models.CharField(max_length=7)),
                ('rgb_value', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_overrides', to='builder.publishedpage')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.colorpalette')),
            ],
            options={
                'unique_together': {('page', 'palette', 'variable_name')},
            },
        ),
    ]
