# Generated by Django 5.2.7 on 2026-02-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_customcoloroverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateColorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.JSONField(default=dict, help_text='All color variables found in template')),
                ('suggested_mapping', models.JSONField(blank=True, default=dict)),
                ('custom_mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_count', models.IntegerField(default=0, help_text='Number of times this template has been scanned')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_mapping', to='builder.template')),
            ],
            options={
                'verbose_name': 'Template Color Mapping',
                'verbose_name_plural': 'Template Color Mappings',
            },
        ),
    ]
