# Generated by Django 5.2.7 on 2026-02-12 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0020_templatecolormapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteTemplateCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_mapping', models.JSONField(default=dict, help_text='Map palette color roles to template variable names')),
                ('usage_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.colorpalette')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.template')),
            ],
            options={
                'unique_together': {('palette', 'template')},
            },
        ),
        migrations.AddField(
            model_name='colorpalette',
            name='compatible_templates',
            field=models.ManyToManyField(blank=True, help_text='Templates this palette has been optimized for', through='builder.PaletteTemplateCompatibility', to='builder.template'),
        ),
    ]
