# Generated by Django 5.2.7 on 2026-02-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0021_palettetemplatecompatibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecolorpalette',
            name='variable_mapping',
            field=models.JSONField(default=dict, help_text='Map palette color roles to template variable names'),
        ),
    ]
