# Generated by Django 5.2.7 on 2026-02-12 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0022_pagecolorpalette_variable_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpage',
            name='active_palette',
            field=models.ForeignKey(blank=True, help_text='Currently active color palette for this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_pages', to='builder.colorpalette'),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='active_palette_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Cached colors from the active palette', null=True),
        ),
    ]
