# Generated by Django 5.2.7 on 2026-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0023_publishedpage_active_palette_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagecolorpalette',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pagecolorpalette',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('page', 'is_active'), name='unique_active_palette_per_page'),
        ),
    ]
