# Generated by Django 5.2.7 on 2026-02-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0024_fix_palette_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalettecolor',
            name='last_synced_value',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='colorpalettecolor',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of elements using this color'),
        ),
        migrations.CreateModel(
            name='PaletteColorUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(db_index=True, max_length=100)),
                ('current_hex_value', models.CharField(max_length=7)),
                ('element_count', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_usages', to='builder.publishedpage')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.colorpalette')),
                ('palette_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.colorpalettecolor')),
            ],
            options={
                'indexes': [models.Index(fields=['page', 'variable_name'], name='builder_pal_page_id_ed0627_idx'), models.Index(fields=['last_synced'], name='builder_pal_last_sy_339641_idx')],
                'unique_together': {('page', 'palette', 'palette_color', 'variable_name')},
            },
        ),
    ]
