# Generated by Django 5.2.7 on 2026-02-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0025_colorpalettecolor_last_synced_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Specification title (e.g., 'Material', 'Warranty')", max_length=200)),
                ('value', models.CharField(help_text="Specification value (e.g., 'Cotton', '2 Years')", max_length=500)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which specifications appear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_specs', to='builder.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
