# Generated by Django 5.2.7 on 2026-02-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0026_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpage',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso (MX$)'), ('CHF', 'Swiss Franc (Fr)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('KRW', 'South Korean Won (₩)')], default='USD', help_text='Store currency', max_length=3),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='currency_position',
            field=models.CharField(choices=[('before', 'Before amount ($10)'), ('after', 'After amount (10$)'), ('before_space', 'Before with space ($ 10)'), ('after_space', 'After with space (10 $)')], default='before', help_text='Position of currency symbol', max_length=15),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol for display', max_length=10),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='decimal_places',
            field=models.IntegerField(choices=[(0, '0 (10)'), (1, '1 (10.5)'), (2, '2 (10.50)'), (3, '3 (10.500)')], default=2, help_text='Number of decimal places'),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='decimal_separator',
            field=models.CharField(choices=[('.', 'Period (10.50)'), (',', 'Comma (10,50)')], default='.', help_text='Decimal separator', max_length=2),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='payment_currency_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Mappings for different payment gateways'),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='thousand_separator',
            field=models.CharField(choices=[(',', 'Comma (1,000)'), ('.', 'Period (1.000)'), (' ', 'Space (1 000)'), ('', 'None (1000)')], default=',', help_text='Thousand separator', max_length=1),
        ),
    ]
