# Generated by Django 5.2.7 on 2026-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0027_publishedpage_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpage',
            name='currency_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete currency data including formatting rules'),
        ),
        migrations.AlterField(
            model_name='publishedpage',
            name='currency_code',
            field=models.CharField(default='USD', help_text='Store currency code (e.g., USD, EUR, GBP)', max_length=10),
        ),
    ]
