# Generated by Django 5.2.7 on 2026-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0028_publishedpage_currency_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedpage',
            name='currency_data',
        ),
        migrations.AlterField(
            model_name='publishedpage',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso (MX$)'), ('CHF', 'Swiss Franc (Fr)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('KRW', 'South Korean Won (₩)')], default='USD', help_text='Store currency', max_length=3),
        ),
    ]
