# Generated by Django 5.2.7 on 2026-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0030_alter_publishedpage_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpage',
            name='currency',
            field=models.CharField(default='USD', help_text='Store currency (e.g., USD, EUR, GBP)', max_length=3),
        ),
    ]
