# Generated by Django 5.2.7 on 2026-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0032_alter_publishedpage_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedpage',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('XAF', 'Central African CFA Franc'), ('XOF', 'West African CFA Franc'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('KES', 'Kenyan Shilling'), ('ZAR', 'South African Rand'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee')], default='XAF', help_text='Store currency (e.g., USD, EUR, GBP)', max_length=3),
        ),
    ]
