# Generated by Django 5.2.7 on 2026-02-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0033_alter_publishedpage_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedpage',
            name='currency',
        ),
    ]
