# Generated by Django 5.2.7 on 2026-02-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0034_remove_publishedpage_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_time', models.CharField(blank=True, default='1-3 business days', max_length=100)),
                ('shipping_methods', models.TextField(blank=True, help_text='Describe shipping methods and rates')),
                ('delivery_timeframe', models.CharField(blank=True, default='5-10 business days', max_length=100)),
                ('free_shipping_threshold', models.CharField(blank=True, default='Orders over $50', max_length=100)),
                ('return_window', models.CharField(blank=True, default='30 days', max_length=100)),
                ('return_conditions', models.TextField(blank=True, help_text='Conditions for returns')),
                ('return_process', models.TextField(blank=True, help_text='How to initiate a return')),
                ('refund_info', models.TextField(blank=True, help_text='Refund process and timeline')),
                ('international_shipping', models.TextField(blank=True)),
                ('support_contact', models.CharField(blank=True, help_text='Email or contact link', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_policy', to='builder.publishedpage')),
            ],
            options={
                'verbose_name_plural': 'Shipping Policies',
            },
        ),
    ]
