# Generated by Django 5.2.7 on 2026-02-20 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0035_shippingpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('threads', 'Threads'), ('discord', 'Discord'), ('github', 'GitHub'), ('medium', 'Medium'), ('tumblr', 'Tumblr'), ('reddit', 'Reddit'), ('etsy', 'Etsy'), ('amazon', 'Amazon'), ('ebay', 'eBay'), ('aliexpress', 'AliExpress'), ('shopify', 'Shopify'), ('custom', 'Custom Link')], max_length=20)),
                ('handle', models.CharField(help_text='Your username or full URL', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Custom display name (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('open_in_new_tab', models.BooleanField(default=True, help_text='Open link in new tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='builder.publishedpage')),
            ],
            options={
                'ordering': ['display_order', 'platform'],
                'unique_together': {('page', 'platform')},
            },
        ),
    ]
