# Generated by Django 5.2.7 on 2026-02-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0036_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='handle',
            new_name='raw_handle',
        ),
    ]
