# Generated by Django 5.2.7 on 2026-02-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0037_rename_handle_socialmedia_raw_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Full privacy policy content')),
                ('introduction', models.TextField(blank=True, help_text='Introduction section')),
                ('information_collected', models.TextField(blank=True, help_text='What information we collect')),
                ('how_we_use', models.TextField(blank=True, help_text='How we use your information')),
                ('cookies', models.TextField(blank=True, help_text='Cookie policy')),
                ('third_party', models.TextField(blank=True, help_text='Third-party disclosure')),
                ('data_security', models.TextField(blank=True, help_text='Data security measures')),
                ('your_rights', models.TextField(blank=True, help_text='Your privacy rights')),
                ('children_privacy', models.TextField(blank=True, help_text="Children's privacy")),
                ('international_transfers', models.TextField(blank=True, help_text='International data transfers')),
                ('policy_changes', models.TextField(blank=True, help_text='Changes to this policy')),
                ('contact_info', models.TextField(blank=True, help_text='Contact for privacy questions')),
                ('gdpr_compliant', models.BooleanField(default=False, help_text='GDPR compliant')),
                ('ccpa_compliant', models.BooleanField(default=False, help_text='CCPA compliant')),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='builder.publishedpage')),
            ],
            options={
                'verbose_name_plural': 'Privacy Policies',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Full terms and conditions content')),
                ('introduction', models.TextField(blank=True, help_text='Introduction section')),
                ('agreement_to_terms', models.TextField(blank=True, help_text='Agreement to terms section')),
                ('intellectual_property', models.TextField(blank=True, help_text='Intellectual property section')),
                ('user_responsibilities', models.TextField(blank=True, help_text='User responsibilities section')),
                ('prohibited_activities', models.TextField(blank=True, help_text='Prohibited activities section')),
                ('termination', models.TextField(blank=True, help_text='Termination section')),
                ('governing_law', models.TextField(blank=True, help_text='Governing law section')),
                ('disputes', models.TextField(blank=True, help_text='Dispute resolution section')),
                ('limitations', models.TextField(blank=True, help_text='Limitations of liability section')),
                ('contact_info', models.TextField(blank=True, help_text='Contact information for legal inquiries')),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='builder.publishedpage')),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
    ]
