# Generated by Django 5.2.7 on 2026-02-25 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0039_alter_taxclass_unique_together_remove_taxclass_page_and_more'),
        ('payments', '0006_taxclass_taxrate_taxreport_taxtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='payments.taxclass'),
        ),
    ]
