# Generated by Django 5.2.7 on 2026-02-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0040_product_tax_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpage',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
