# Generated by Django 5.2.7 on 2026-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0041_publishedpage_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a category image or icon', null=True, upload_to='category_images/'),
        ),
    ]
