# Generated by Django 5.2.7 on 2026-03-10 21:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0043_alter_backgroundimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalettecolor',
            name='hex_value',
            field=models.CharField(help_text='Hex color code (e.g., #4361ee)', max_length=30),
        ),
        migrations.AlterField(
            model_name='colorpalettecolor',
            name='last_synced_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='component_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='customcoloroverride',
            name='hex_value',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='iconcustomization',
            name='color',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='palettecolorusage',
            name='current_hex_value',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/main/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a category image or icon', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product-images/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_variants/'),
        ),
        migrations.AlterField(
            model_name='stylecustomization',
            name='background_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stylecustomization',
            name='text_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='template_previews/'),
        ),
    ]
