# Generated by Django 5.2.7 on 2026-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0044_alter_colorpalettecolor_hex_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_free_shipping_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_shipping_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Rate'), ('free', 'Free Shipping'), ('per_item', 'Per Item'), ('calculated', 'Calculated by Quantity')], default='flat', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_separately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='use_custom_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
