# Generated by Django 5.2.7 on 2026-06-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0047_alter_productvariant_options_productvariant_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='builder.productvariant'),
        ),
    ]
