# Generated by Django 5.2.7 on 2026-06-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0048_cartitem_selected_options_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptionvalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
