# Generated by Django 5.2.7 on 2026-06-27 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0049_productoptionvalue_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.productinventory'),
        ),
    ]
