# Generated by Django 5.2.7 on 2026-07-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0050_alter_productvariant_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpage',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publishedpage',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
