# Generated by Django 5.2.7 on 2026-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0050_alter_productvariant_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylecustomization',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS for this element', null=True),
        ),
    ]
