# Generated by Django 5.2.7 on 2026-07-17 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0051_stylecustomization_custom_css'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('industry', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('palette', models.CharField(max_length=50)),
                ('customizations', models.JSONField(help_text='Complete page_customizations JSON from AI generation')),
                ('hero_image', models.ImageField(blank=True, help_text='Sample hero image for this design', null=True, upload_to='ai_design_heroes/')),
                ('is_used', models.BooleanField(default=False)),
                ('used_count', models.IntegerField(default=0)),
                ('max_uses', models.IntegerField(default=1, help_text='How many times this design can be used (1 = unique per user)')),
                ('used_by_users', models.JSONField(blank=True, default=list, help_text='List of user IDs who used this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this design')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['industry', 'style', 'palette'], name='builder_aid_industr_245d56_idx'), models.Index(fields=['is_used'], name='builder_aid_is_used_cf09f2_idx')],
                'unique_together': {('industry', 'style', 'palette')},
            },
        ),
    ]
