# Generated by Django 5.2.7 on 2026-07-17 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0052_aidesigntemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidesigntemplate',
            options={'ordering': ['industry', 'style', 'palette', '-version']},
        ),
        migrations.AlterUniqueTogether(
            name='aidesigntemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aidesigntemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active designs are used'),
        ),
        migrations.AddField(
            model_name='aidesigntemplate',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for this combination'),
        ),
        migrations.AddIndex(
            model_name='aidesigntemplate',
            index=models.Index(fields=['is_active'], name='builder_aid_is_acti_01c284_idx'),
        ),
    ]
