# Generated by Django 5.2.7 on 2026-08-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0051_publishedpage_contact_number_publishedpage_country'),
        ('builder', '0053_alter_aidesigntemplate_options_and_more'),
    ]

    operations = [
    ]
