# Generated by Django 5.2.7 on 2026-08-08 15:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0054_merge_20260804_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylecustomization',
            name='custom_css',
        ),
        migrations.AlterField(
            model_name='cjsettings',
            name='access_token',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='variant_images/'),
        ),
        migrations.DeleteModel(
            name='AIDesignTemplate',
        ),
    ]
