# Generated by Django 5.2.7 on 2026-08-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0055_remove_stylecustomization_custom_css_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDisplayMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('single', 'Single Product with Swatches'), ('grouped', 'Grouped by Attribute'), ('flattened', 'Flatten All Variants')], default='single', max_length=20)),
                ('group_by', models.CharField(default='image', max_length=20)),
                ('primary_attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('cached_groups', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_mode', to='builder.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_groups/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_groups', to='builder.product')),
                ('variants', models.ManyToManyField(related_name='variant_groups', to='builder.productvariant')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('product', 'group_key')},
            },
        ),
    ]
