# Generated by Django 5.2.7 on 2026-08-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0056_productdisplaymode_variantgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgroup',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
