# Generated by Django 5.2.7 on 2026-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0057_variantgroup_is_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgroup',
            name='primary_attribute_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
