# Generated by Django 5.2.7 on 2026-08-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0058_variantgroup_primary_attribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisplaymode',
            name='cached_groups',
        ),
        migrations.AlterField(
            model_name='productdisplaymode',
            name='group_by',
            field=models.CharField(choices=[('image', 'Group by Image'), ('primary_attribute', 'Primary Attribute'), ('none', 'No Grouping')], default='image', max_length=20),
        ),
        migrations.CreateModel(
            name='GroupedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_ids', models.JSONField(default=list, help_text='List of variant IDs in this group')),
                ('group_key', models.CharField(max_length=100)),
                ('group_display_name', models.CharField(max_length=200)),
                ('original_status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_products', to='builder.product')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_source', to='builder.product')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('original_product', 'group_key')},
            },
        ),
    ]
