# Generated by Django 5.2.7 on 2026-08-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0060_editorimage_editormedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tiers', to='builder.publishedpage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='builder.product')),
            ],
            options={
                'ordering': ['display_order', 'quantity'],
                'unique_together': {('product', 'quantity')},
            },
        ),
    ]
