# Generated by Django 5.2.7 on 2026-08-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0061_producttier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
