# Generated by Django 5.2.7 on 2026-08-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0062_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
