# Generated by Django 5.2.7 on 2026-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='auto_convert',
            field=models.BooleanField(default=True, help_text='Automatically convert store currency to target currency'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='target_currency',
            field=models.CharField(default='USD', help_text='Currency to convert to before sending to gateway', max_length=3),
        ),
    ]
