# Generated by Django 5.2.7 on 2026-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentgateway_auto_convert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency used for payment', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='store_currency',
            field=models.CharField(default='USD', help_text='Original store currency', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
