# Generated by Django 5.2.7 on 2026-02-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_conversion_rate_order_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store_currency',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='auto_convert',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='target_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_currency',
        ),
    ]
