# Generated by Django 5.2.7 on 2026-02-25 04:35

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_order_conversion_rate_remove_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='facebook_messenger_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='instagram_business_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='social_media_auto_send',
            field=models.BooleanField(default=True, help_text='Automatically send order details to social media'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='social_media_message_template',
            field=models.TextField(blank=True, help_text='Custom message template for social media orders', null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='social_media_order_prefix',
            field=models.CharField(default='SOC-', help_text='Prefix for social media order numbers', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='social_media_platforms',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled social media platforms'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='telegram_bot_token',
            field=payments.models.EncryptedField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='whatsapp_business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='x_dm_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='x_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay'), ('fincra', 'Fincra'), ('cryptomus', 'Cryptomus'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('pay_on_delivery', 'Pay on Delivery'), ('social_media', 'Social Media')], max_length=20),
        ),
    ]
