# Generated by Django 5.2.7 on 2026-02-25 19:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0039_alter_taxclass_unique_together_remove_taxclass_page_and_more'),
        ('payments', '0005_paymentgateway_facebook_messenger_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('is_shipping_taxable', models.BooleanField(default=False, help_text='Apply tax to shipping costs')),
                ('is_compound', models.BooleanField(default=False, help_text='Apply on top of other taxes')),
                ('is_default', models.BooleanField(default=False, help_text='Default tax class for new products')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_classes', to='builder.publishedpage')),
            ],
            options={
                'verbose_name': 'Tax Class',
                'verbose_name_plural': 'Tax Classes',
                'ordering': ['name'],
                'unique_together': {('page', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate percentage (e.g., 10.0000 for 10%)', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('jurisdiction_type', models.CharField(choices=[('country', 'Country'), ('state', 'State/Province'), ('city', 'City'), ('postal_code', 'Postal Code'), ('special', 'Special Zone')], default='country', max_length=20)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('state_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('postal_code_match_pattern', models.CharField(blank=True, help_text='Regex pattern for postal code matching', max_length=100)),
                ('priority', models.IntegerField(choices=[(0, 'Priority 0'), (1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3'), (4, 'Priority 4'), (5, 'Priority 5'), (6, 'Priority 6'), (7, 'Priority 7'), (8, 'Priority 8'), (9, 'Priority 9')], default=0, help_text='Lower numbers apply first')),
                ('is_compound', models.BooleanField(default=False, help_text='Apply on top of other taxes')),
                ('is_price_inclusive', models.BooleanField(default=False, help_text='Tax is included in product price')),
                ('is_shipping_taxable', models.BooleanField(default=False, help_text='Apply to shipping costs')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='builder.publishedpage')),
                ('tax_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payments.taxclass')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['priority', 'country_code', 'state_code', 'city'],
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='tax_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='builder.publishedpage')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_applied', models.DecimalField(decimal_places=4, max_digits=6)),
                ('jurisdiction_type', models.CharField(max_length=20)),
                ('jurisdiction_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('applied', 'Applied'), ('refunded', 'Refunded'), ('voided', 'Voided')], default='calculated', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('customer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='payments.order')),
                ('tax_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.taxclass')),
                ('tax_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.taxrate')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxExemptCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, help_text='VAT/Tax ID number', max_length=50)),
                ('exemption_reason', models.CharField(blank=True, choices=[('reseller', 'Reseller'), ('nonprofit', 'Non-profit Organization'), ('government', 'Government Entity'), ('wholesale', 'Wholesale Customer'), ('tax_exempt', 'Tax Exempt'), ('other', 'Other')], max_length=20)),
                ('exempt_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('exempt_until', models.DateTimeField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='tax_certificates/')),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exemptions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_exempt_customers', to='builder.publishedpage')),
            ],
            options={
                'verbose_name': 'Tax Exempt Customer',
                'verbose_name_plural': 'Tax Exempt Customers',
                'ordering': ['-created_at'],
                'unique_together': {('page', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['country_code', 'state_code'], name='payments_ta_country_3cfe4a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tax_class', 'is_active'], name='payments_ta_tax_cla_179af4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['valid_from', 'valid_until'], name='payments_ta_valid_f_ad7a9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxreport',
            unique_together={('page', 'report_type', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['order'], name='payments_ta_order_i_c3222c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['transaction_id'], name='payments_ta_transac_e08702_idx'),
        ),
    ]
