# Generated by Django 5.2.7 on 2026-03-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0044_alter_colorpalettecolor_hex_value_and_more'),
        ('payments', '0006_taxclass_taxrate_taxreport_taxtransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('both', 'Both')], default='shipping', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='builder.publishedpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Domestic, International, Europe', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Internal description')),
                ('zone_type', models.CharField(choices=[('domestic', 'Domestic'), ('regional', 'Regional'), ('international', 'International'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('countries', models.JSONField(default=list, help_text='List of country codes')),
                ('regions', models.JSONField(blank=True, default=dict, help_text='Optional: Regions per country')),
                ('postcode_patterns', models.JSONField(blank=True, default=list, help_text='Regex patterns for postcodes')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Higher number appears first')),
                ('show_in_checkout', models.BooleanField(default=True)),
                ('show_estimated_delivery', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='builder.publishedpage')),
            ],
            options={
                'ordering': ['-display_order', 'name'],
                'unique_together': {('page', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Shipping, Express', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Rate'), ('calculated', 'Calculated by Weight/Price'), ('free', 'Free Shipping'), ('local_pickup', 'Local Pickup')], default='flat', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('condition_type', models.CharField(blank=True, choices=[('weight', 'By Weight'), ('price', 'By Order Price')], max_length=20)),
                ('price_tiers', models.JSONField(blank=True, default=list, help_text='Price tiers')),
                ('weight_tiers', models.JSONField(blank=True, default=list, help_text='Weight tiers')),
                ('free_shipping_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_shipping_min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_min_days', models.IntegerField(default=3)),
                ('delivery_max_days', models.IntegerField(default=7)),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('carrier_service', models.CharField(blank=True, max_length=50)),
                ('requires_shipping', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('taxable', models.BooleanField(default=True, help_text='Apply tax to shipping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payments.shippingzone')),
            ],
            options={
                'ordering': ['-display_order', 'price'],
            },
        ),
    ]
