# Generated by Django 5.2.7 on 2026-04-13 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_order_shipping_carrier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('free', 'Starter - Free'), ('pro', 'Pro - $12/mo'), ('business', 'Business - $29/mo'), ('agency', 'Agency - $79/mo')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_websites', models.IntegerField(default=1, help_text='-1 for unlimited')),
                ('max_products', models.IntegerField(default=10, help_text='-1 for unlimited')),
                ('max_storage_mb', models.IntegerField(default=100, help_text='-1 for unlimited')),
                ('max_visitors', models.IntegerField(default=1000, help_text='Monthly, -1 for unlimited')),
                ('max_form_submissions', models.IntegerField(default=10, help_text='Monthly, -1 for unlimited')),
                ('max_emails', models.IntegerField(default=0, help_text='Monthly, 0 for none')),
                ('custom_domain', models.BooleanField(default=False)),
                ('remove_branding', models.BooleanField(default=False)),
                ('advanced_seo', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('email_marketing', models.BooleanField(default=False)),
                ('abandoned_cart', models.BooleanField(default=False)),
                ('discount_codes', models.BooleanField(default=False)),
                ('white_label', models.BooleanField(default=False)),
                ('custom_templates', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('badge', models.CharField(blank=True, help_text="e.g., 'Most Popular'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Free Plan'), ('pending', 'Payment Pending'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='free', max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, help_text="e.g., 'Bank Transfer', 'Cash', 'Mobile Money'", max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='payments_su_user_id_058311_idx'), models.Index(fields=['status', 'end_date'], name='payments_su_status_79c6da_idx')],
            },
        ),
    ]
