# Generated by Django 5.2.7 on 2026-04-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_plan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='downgrade_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='downgrade_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_downgrades', to='payments.plan'),
        ),
    ]
