# Generated by Django 5.2.7 on 2026-02-11 16:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveBigIntegerField(default=0)),
                ('unique_visitors', models.PositiveBigIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration', models.DurationField(default=datetime.timedelta(0))),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='builder.publishedpage')),
            ],
            options={
                'verbose_name_plural': 'Website Analytics',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click'), ('form_submit', 'Form Submit'), ('purchase', 'Purchase'), ('download', 'Download'), ('scroll', 'Scroll'), ('video_play', 'Video Play'), ('social_share', 'Social Share')], max_length=50)),
                ('event_name', models.CharField(max_length=200)),
                ('element_id', models.CharField(blank=True, max_length=100, null=True)),
                ('element_class', models.CharField(blank=True, max_length=200, null=True)),
                ('element_text', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.websiteanalytics')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('conversion_type', models.CharField(choices=[('purchase', 'Purchase'), ('form_submit', 'Form Submission'), ('signup', 'Sign Up'), ('contact', 'Contact'), ('download', 'Download'), ('newsletter', 'Newsletter Signup')], max_length=50)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='analytics.websiteanalytics')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_type', models.CharField(choices=[('direct', 'Direct'), ('organic', 'Organic Search'), ('social', 'Social Media'), ('referral', 'Referral'), ('email', 'Email'), ('paid', 'Paid Search')], max_length=20)),
                ('source_name', models.CharField(max_length=200)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='analytics.websiteanalytics')),
            ],
            options={
                'unique_together': {('analytics', 'date', 'source_type', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('visitor_id', models.CharField(max_length=100)),
                ('page_url', models.CharField(max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], max_length=20)),
                ('browser', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_bounce', models.BooleanField(default=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.websiteanalytics')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_p_timesta_835321_idx'), models.Index(fields=['session_id'], name='analytics_p_session_a580f2_idx'), models.Index(fields=['visitor_id'], name='analytics_p_visitor_4184ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_data', to='analytics.websiteanalytics')),
            ],
            options={
                'unique_together': {('analytics', 'date', 'country', 'region', 'city')},
            },
        ),
    ]
