# Generated by Django 5.2.7 on 2026-04-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='page_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
